### PR TITLE
Add sub-method mapping to allow $json->foo->bar->baz() mapping to foo.bar.baz()

### PR DESCRIPTION
**Pull request by scottchiefbaker**
This gives us access to name spaces in JSON-RPC

### CODE REVIEW

**Comment by claesjac** [comment]
I don't like this as it would break a future possibility to call methods with no arguments instead of passing {} or []. Needs another syntax

**Comment by scottchiefbaker** [comment]
On 02/07/2014 12:06 AM, Claes Jakobsson wrote:

> I don't like this as it would break a future possibility to call methods
> with no arguments instead of passing {} or []. Needs another syntax

I didn't even think of no argument functions... Those are pretty
uncommon. In all the APIs I've dealt with I think only one had a
function that didn't require arguments.

That said you could always do: $obj->foo->bar->baz(undef);

To get the same effect. If that's not acceptable I guess we'll have to
adopt a call routine like JSON::RPC:

$obj->call('foo.bar.method',@parameters);

What do you think? It's not as intuitive, but it'll work.

**Comment by scottchiefbaker** [comment]
What can do we about namespaced calls? They're pretty crucial to my application, and I'd really like to continue to use `JSON::RPC::Simple`.

**Comment by claesjac** [comment]
Been busy and haven't had time to think about it. One option would be to replace all _ in the calling method name with a period. However, the specification for 1.1 WD (which this module implements) only says what method names SHOULD and not MUST adhere. I'm not going to add a call method for general calls as this can conflict with a call method that someone might be calling today.

One option would be something like { local $client->{namespace} = "foo.bar"; $client->baz(...) } and that would call foo.bar.baz

**Comment by scottchiefbaker** [comment]
I think:

`$obj->call('foo.bar.method',\@parameters);`

Sounds pretty good

**Pull request closed without merging**
